name: bda-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - pyarrow=14.0.2
  - matplotlib
  - astropy
  - dask
  - ipykernel
  - pip
  - pyspark=3.5.0
  - findspark
  - openjdk=11
  - pip:
    - kafka-python
    - msgpack